# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nmf <- function(Y, k, maxit, tol) {
    .Call('_GRACKLE_nmf', PACKAGE = 'GRACKLE', Y, k, maxit, tol)
}

nmf_with_graph_regularization <- function(Y, S_P, S_G, k, lambda1, lambda2, maxit) {
    .Call('_GRACKLE_nmf_with_graph_regularization', PACKAGE = 'GRACKLE', Y, S_P, S_G, k, lambda1, lambda2, maxit)
}

