# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Euclidean Distance Matrix
#'
#' @param X A numeric matrix where rows represent observations and columns represent variables.
#' @return A numeric matrix representing the pairwise Euclidean distances between rows of the input matrix.
#' @export
euclideanDist <- function(X) {
    .Call('_GRACKLE_euclideanDist', PACKAGE = 'GRACKLE', X)
}

